# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(max_length=100, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('preview', models.ImageField(upload_to='main_products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'main_product',
                'verbose_name': '\u041a\u0443\u0440\u043e\u0447\u043a\u0430',
                'verbose_name_plural': '\u041a\u0443\u0440\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u044a\u0451\u043c')),
            ],
            options={
                'db_table': 'product_sizes',
                'verbose_name': ('\u041e\u0431\u044a\u0451\u043c',),
                'verbose_name_plural': '\u041e\u0431\u044a\u0451\u043c\u044b',
            },
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='sizes',
            field=models.ManyToManyField(to='koko_models.ProductSizes', verbose_name='\u041e\u0431\u044a\u0451\u043c\u044b'),
        ),
    ]
