# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koko_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('preview', models.ImageField(upload_to='drinking_products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
            ],
            options={
                'db_table': 'drinking_product',
                'verbose_name': '\u041d\u0430\u043f\u0438\u0442\u043e\u043a',
                'verbose_name_plural': '\u041d\u0430\u043f\u0438\u0442\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='PotatoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(max_length=100, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('preview', models.ImageField(upload_to='potato_products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('sizes', models.ManyToManyField(to='koko_models.ProductSizes', verbose_name='\u041e\u0431\u044a\u0451\u043c\u044b')),
            ],
            options={
                'db_table': 'potato_product',
                'verbose_name': '\u041a\u0430\u0440\u0442\u043e\u0444\u0435\u043b\u044c',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u043e\u0444\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='SaladeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('preview', models.ImageField(upload_to='salade_products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
            ],
            options={
                'db_table': 'salade_product',
                'verbose_name': '\u0421\u0430\u043b\u0430\u0442',
                'verbose_name_plural': '\u0421\u0430\u043b\u0430\u0442\u044b',
            },
        ),
    ]
