# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koko_models', '0004_auto_20161201_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='score',
            field=models.FloatField(default=0, verbose_name='\u0418\u0442\u043e\u0433\u043e'),
        ),
    ]
