# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koko_models', '0007_order_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='time_of_work',
            field=models.CharField(default='10:00 - 22:00', max_length=255, verbose_name='Chasy raboty'),
        ),
    ]
